### ISSUE TITLE
Imagine RIT 2023

### ISSUE THREAD

**Issue by Mster115** [all-rit/ALL#174]
### Description
ImagineRIT 2023 is an empathy focused exercise that incorporates Lab 2's colorblindness activity. Participants will go through the activity as presented in Lab 2 up until repair; following this, they will watch a video of a subject doing a version of the exercise they just participated in. The goal is for the participant to recognize and document whenever the subject goes through emotional discomfort.

### Issues
- [x] #173 

### Stories / Tasks
- [ ] About
- [ ] Exercise Part I: Experiantial Based Intervention
- [ ] Exercise Part II: Expression Based Intervention
- [ ] Reinforcement

### Acceptance Criteria
- [x] Complete initial design
- [ ] Complete Design Wireframe
- [ ] Given when the user starts the exercise, they should be presented with an about page expressing the importance of empathy and explaining the exercise
- [ ] Given when the user completes reading the about section, they should be able to click on a button that will redirect them to Exercise Part I 
- [ ] Given when the Exercise starts, the user should be able to play a shortend version of the game portion of Lab 2; starting from the ball selection game, ending with the CB emulation version
- [ ] Given when the user completes Exercise Part I,  they should be able to click on a button that will redirect them to Exercise Part II
- [ ] Exercise Part II requires a video component. We require people to be in the video. Reach out to Su for Outreach **HIGH_PRIORITY**
- [ ] Given when the user clicks the button after Exercise Part I, they should be redirected to a page explaining Exercise Part II
- [ ] Given when the user is done reading the explanation for Exercise Part II, there should be a button to direct them to the exercise
- [ ] Given the user presses the button to redirect to Exercise Part II, the user should be presented with a page that has a video with a subject doing a version of Exercise Part I, there will also be a button on the bottom of the screen
- [ ] Given the user clicks the video, the video starts
- [ ] Given the user clicks the button in the correct time frame, add 1 to a counter that keeps track of how accurately someone detects discomfort
- [ ] Given that the user completes the video, a button unlocks and redirects the user to a results page
- [ ] Given that the user clicks on the results page button, they are shown a page that shows the results of the exercise they partook in (**You detected emotion x/5 times! Good job!**)
