### ISSUE TITLE
Lab 7: AI Security

### ISSUE THREAD

**Issue by Mster115** [all-rit/ALL#175]
### Description
Lab 7 is concerned with providing participants with a fundamental understanding of the core aspects of autonomous systems through a cybersecurity focus, which is a significant area of application for AI and Machine Learning. To strengthen this understanding, the participant will progress through a simulation of an autonomous system that will modify the access of sensitive files when security threats are present in the system.

### Stories / Tasks / Issues (Pending)
- [x] Reading
- [x] #142 [Phase 1: Simulation](https://github.com/all-rit/ALL/issues/142)
- [x] #143 [Phase 2: Improving The Autonomous System](https://github.com/all-rit/ALL/issues/143)
- [x] #144 [Phase 3: Alteration Activity](https://github.com/all-rit/ALL/issues/144)
- [x] Quiz

### Acceptance Criteria
- [x] Given when the user starts the lab, then they should be prompted with a reading exercise that details the importance of cybersecurity and AI
- [x] Given when the user completes the reading exercise, then they should be able to click on a button that will redirect them to the exercise portion of the lab
- [x] Given when the user starts the simulation, the autonomous system will complete the simulation without requiring user input/interaction
- [x] Given when the simulation starts, the autonomous system should simulate ten rounds where random threats of varying levels will be fed into the system
- [x] Given when the autonomous system completes the simulation, a table containing results from the ten rounds should be rendered
- [x] Given when the user starts the second exercise, then they should be able to alter the utility equation to improve the accuracy of the system's decision making
- [x] Given when the user completes the coding exercise, a simulation should be executed with the updated equation
- [x] Given when the user makes changes to the code, then they should be able to rerun the simulation as many times as they would like
- [x] Given when the user starts the alteration activity, then they should be prompted with five multiple-choice questions
- [x] Given when the user completes the activity, then a table including the questions, their answers, and the correct answers should be rendered
- [x] Given when the user completes the activity, then they should be able to click on a button that will redirect them to the reinforcement portion of the lab
- [x] Given when the user completes the reinforcement activity, then they should be able to click on a button that will redirect them to the quiz of the lab

### Links
[Quick notes from documentation](https://docs.google.com/document/d/1d9xtCv3MX7EdE_Lem__ri7u576eOZbHHmS_xlJX3vs8/edit)
[Reading Writeup](https://docs.google.com/document/d/1SEsZeuRDYEkQRLD96Rny9vc9Z9GsGVq4Q3ciJxifTUg/edit#heading=h.pq2xmyv3uvtj)
[Lab Details](https://docs.google.com/document/d/18pL0aDnVMHwPmS1M41HbUkI4veyDo5URaoBNJQzyGbo/edit#)
[Figma](https://www.figma.com/file/j1poSQHZysuj08zQFLL9IJ/Lab-7)
