### ISSUE TITLE
Imagine RIT 2022 Lab Conversion

### ISSUE THREAD

**Issue by Mster115** [all-rit/ALL#176]
# Description

Lab 8 

# Tasks

- [x] #179 
    - [x] Write an about section
    - [x] Proofread and edit the final about section
- [x] #180 
    - [x] Read over and edit the reading section rough draft
    - [x] Research Chat GPT to include as an example
    - [x] Proofread and edit the final reading section
- [x] Exercise section
    - [x] #230 
    - [x] #231 
    - [x] #232  
- [x] #177 
    - [x] Everyone research and find 2 videos
    - [x] Choose the best 2 videos
- [x] #178 
    - [x] Everyone add 1-3 quiz questions
    - [x] Choose the best 4-5 questions

# Resources

1. [Summary of Previously Created Activity and Research Questions](https://docs.google.com/document/d/1oLwBF1dp3ObR0eUUTwQQGqCDJPtv3aXtWfdX9S4EwtU/edit)
2. [Reading Section Rough Draft](https://docs.google.com/document/d/1El47Ei0AThU5nuVH0xQGjjYHDiUn1-MCtUJfbV9NU64/edit#heading=h.rurk2ijw889q)
3. [Activity Wireframes](https://www.figma.com/file/YOYDy3PbcBXzRUGrgw0cnX/Imagine-RIT-Tic-Tac-Toe?node-id=0%3A1&t=dDuel1fmxm5Eb2jr-0)
4. [Published Paper With Results From Imagine Study](https://drive.google.com/file/d/1Sp9uXhet_AOxYHC6KhHn6PLKU3js_HOf/view?usp=share_link)
