### ISSUE TITLE
Continuous Integration and Deployment Pipeline

### ISSUE THREAD

**Issue by AndreasLc1103** [all-rit/ALL#202]
# Epic

## Description

To ensure better code quality and reliability of the site there has been communication of using CI/CD to aid in continuously testing and deploying new code presented by the team. This Epic is focused on delivering the ability to provide a consistent and automated process to test and deploy to our test and development environments.

### Stories and task

- [x]  Research Spike on tools and options

- [ ] Create a test pipeline for back-end testing
- [ ] Create a test pipeline for front-end testing
- [x] Create a Deployment pipeline for the front-end
- [x] Create a Deployment pipeline for the back-end

### Acceptance Criteria

- [ ] Given when a developer is merging into prod, then they should see their changes reflected on the production site at [all.rit.edu](https://all.rit.edu/)
- [ ] Given when a developer creates a pull request, then they should have their front-end code tested.
- [ ] Given when a developer creates a pull request, then they should have their back-end code tested.

#### Stories attached 

- [x] #367
