### ISSUE TITLE
Create a data structure for chat messages

### ISSUE THREAD

**Issue by heathermoses** [all-rit/ALL#307]
# Create a data structure to hold chat messages and input the messages

## Description

Once we get our chat messages approved by the professors, we need to create a structure to store our messages in the codebase. 

## Subtasks

- [ ] Create a file a store the chat messages
- [ ] Port over the data structure
- [ ] Fill in messages in the data structure

## Acceptance Criteria

- [ ] Data structure is usable
- [ ] All messages are imported into the data structure

## Resources
[Chat Messages](https://docs.google.com/document/d/1b4HVHetsqQYpPn5UIlcVE3WUyhttObJEDUN6kQWRZxE/edit#)

```js
export const CHAT_MESSAGES = {
  keep: [
    {
      username: "not_a_bot",
      profile: "",
      content: "positive message 1",
      ai_correct: true,
      intended_sentiment_category: 2,
    },
  ],
  remove: [
    {
      username: "gamer123",
      profile: "",
      content: "murder them in the laboratory!",
      ai_correct: false,
      intended_sentiment_category: 1,
    },
  ]
}

export const PREDATA_POINTS = {
  positive: [
    "I am happy",
  ],
  negative: [
    "you suck"
  ],
  neutral: [
    "I am tired today"
  ]
}
```
