### ISSUE TITLE
Add Google Meta Tag to register Subdomiain

### ISSUE THREAD

**Issue by AndreasLc1103** [all-rit/ALL#316]
# Add Google Meta Tag to register Subdomiain

As a developer, I want the site to be a verified domain, so we can use Google authentication.

## Definition of Done

- [x] Acceptance criteria defined
- [x] Solution tasks specified
- [x] Feature branch created
- [ ] ~~Unit tests written (on API code only for now)~~
- [ ] ~~Solution passes full suite of unit tests~~
- [ ] ~~***Design**** documents updated if needed~~
- [ ] ~~Pull request created~~
- [ ] ~~Code is reviewed~~
- [ ] ~~Code is merged to `develop` branch~~
- [ ] ~~Tests pass on CI~~
- [ ] ~~Deployed to staging environment~~
- [x] ~~ Acceptance criteria is met~~

## Acceptance Criteria

- [x] Given accessing the API console through Google, when clicking on the project then the site is verified

## Solution Tasks

- [x] Add React-helmet to the index.js
- [x] deploy to production and verify that the Google subdomain is owned by the team
