### ISSUE TITLE
Finish integrating lab with site architecture

### ISSUE THREAD

**Issue by 2nPlusOne** [all-rit/ALL#331]
# Finish integrating lab with site architecture

## Description

We need to finish integrating the lab with the site architecture. Looks like the footer and navigation alerts for when the user is in a lab won't work correctly until the redux state is set up right.

## Subtasks

- [x] Add lab's reducer to the combineReducers method in the root reducer (main.js in the reducers folder)
- [x] Setup the lab to correctly call reducer actions based on user input and lab navigation
- [x] Create skeleton service to eventually send data to backend.

## Acceptance Criteria

- [x] Given that the lab is in progress, the footer should display "The previously available navigation and accessibility buttons are
              disabled until the exercise is complete."
- [x] Given that the lab is in progress, attempting to click away from the lab will result in an alert saying the lab is currently in progress.
