### ISSUE TITLE
Create a page with a mock IDE for the repair section

### ISSUE THREAD

**Issue by heathermoses** [all-rit/ALL#333]
# Description
After the user reads about sentiment analysis and polarity, they will continue to a repair page where they will make changes to the sentiment analysis dataset in a mock IDE.

# Subtasks
- [x] Create a heading to represent the filename where the repair occurs
- [x] Add the JSON object where the user makes edits to the message polarities
- [x] Add error handling so that the user cannot continue the exercise if they don't enter values for each message
- [x] Add error handling so that the user must enter either 0, 1, or 2 for each message
