### ISSUE TITLE
Make ChatRoom component reusable

### ISSUE THREAD

**Issue by 2nPlusOne** [all-rit/ALL#338]
# Make ChatRoom component reusable

## Description

Making the ChatRoom component reusable by injecting the selectMessages function as a prop instead of defining it in the file scope.

## Subtasks

- [ ] Redefine the select message functions in a separate file
- [ ] Convert the function reference into a prop variable
- [ ] Pass the appropriate function into the component

## Acceptance Criteria

- [ ] Given I have different select message functions, when I inject a given function into the component, the component selects messages according to the function.
