### ISSUE TITLE
Update Current/Past Members on Home Page

### ISSUE THREAD

**Issue by dm9965** [all-rit/ALL#355]
# Update Member Image Carousel on Home Page

## Description

Update the image carousels on the home page in order to have an updated and accurate representation who is currently contributing and have contributed to the project in the past, including name, image, role, time with the project, and a LinkedIn profile link.

## Subtasks

- [ ] Update DataGrip with Current Members Names, preferred image, role, time, and social media link
- [ ] If any member is now an alumni of the project, move into alumni section

## Acceptance Criteria

- [ ] Current and Past Members are properly placed
- [ ] The carousels have an appealing and visually consistent design
- [ ] Each carousel item should contain the name, image, role, time with the project, and a valid LinkedIn profile link for each contributor.
