### ISSUE TITLE
Epic: Develop Universal Code Block

### ISSUE THREAD

**Issue by dm9965** [all-rit/ALL#422]
# Universal Code Block

## User Stories

List the user stories that are associated with this epic.

- [ ] As a DEVELOPER, I want PRE-MADE HTML COMPONENTS, in order to SIMPLIFY THE PROCESS OF BUILDING HTML CODE BLOCKS #link
- [ ] As a DEVELOPER, I want PRE-MADE REACT COMPONENTS, in order to STREAMLINE DEVELOPMENT OF REACT APP CODE BLOCKS #link
- [ ] As a DEVELOPER, I want PRE-MADE JSON COMPONENTS, in order to SIMPLIFY CONSTRUCTION OF JSON FILE STYLE CODE BLOCKS #link
- [ ] As a DEVELOPER, I want PRE-MADE TABBING AND OPERANDS, in order to SIMPLIFY BUILDING IDE LIKE CODE BLOCKS

## Technical Requirements

List the technical requirements for this epic.

- [ ] Create Package in **COMMON** Folder Containing Code Block and Accompanying Components
- [ ] Create HTML-based components for JSON, HTML, and REACT style Code Block applications, as well as operands and spacing
- [ ] Test functionality

## Design Considerations

List any special design considerations for this epic.

- [ ] The Code Block Component is the Parent Component
- [ ] JSON, React, HTML, and Operand/Spacing will be separated in different folders
