### ISSUE TITLE
Task: Update Game Documentation in WIKI to Exercise

### ISSUE THREAD

**Issue by AndreasLc1103** [all-rit/ALL#479]
# <Update Game Documentation in WIKI to Exercise>

## Description
To use the Wiki as a single source of truth for future developers using the project. We will need to update the terminology used in the documentation to enforce this consistency change. This will only cover an individual section and will allow for better understanding for the user trying to interact with creating new labs.
## Subtasks

- [x] Find all uses of Game instead of Exercise
- [x] Change all uses of Exercise

## Acceptance Criteria

- [x] Wiki is still readable and intent is clear
- [x] review it by the senior members of the team to verify that is correct
