### ISSUE TITLE
Task: Update About Page Documentation

### ISSUE THREAD

**Issue by dm9965** [all-rit/ALL#481]
# Create About Page Documentation

## Description

Update the ALL Wiki to include new About section code and description of how it works.

## Subtasks

- [x] Update About Page Documentation Codeblock 
- [x] Update About page component description

## Acceptance Criteria

- [x] Codeblock is updated to match current About page implementation
- [x] New description accurately represents what is occurring in the page
