### ISSUE TITLE
Task: Update Reading Section Page Documentation

### ISSUE THREAD

**Issue by dm9965** [all-rit/ALL#482]
#  Update Reading Section Documentation

## Description

Update documentation for reading section in the ALL Wiki such that it will reflect the updated About section codeblock and description of how it works.

## Subtasks

- [x] Update codeblock to reflect current reading section code, Reading.js
- [x] Update description such that it gives an accurate representation of the flow and operations contained in the Reading.js codeblock

## Acceptance Criteria

- [x] Codeblock is updated and matches current Reading.js implementation
- [x] Description accurately describes how the code works in Reading.js
