### ISSUE TITLE
Task: Update Quiz Documentation

### ISSUE THREAD

**Issue by dm9965** [all-rit/ALL#483]
#  Update Quiz Section Documentation

## Description

Update documentation for quiz section in the ALL Wiki such that it will reflect the how to input a set of Quiz questions into the database.

## Subtasks

- [x] Update codeblock to reflect JSON question structure in the database
- [x] Update description such that it gives an accurate representation of how to create a set of questions and what is required to set correct/incorrect values and multiple correct answers (if need be)

## Acceptance Criteria

- [x] Codeblock is updated and matches current JSON database implementation
- [x] Description accurately describes how to create questions and the developer can now create a quiz section for a new lab
