### ISSUE TITLE
Task: Planning for Spring 2024 Lab Development

### ISSUE THREAD

**Issue by dm9965** [all-rit/ALL#484]
# Spring 2024 Lab Development Planning

## Description

In this task, we must iterate on current lab ideas and elaborate on possible exercises that can be used to implement these new labs. Below is the link to the jamboard currently being used to develop new lab ideas. 

https://jamboard.google.com/d/1onCc_8MlsCC3qmDBoIxMOUx-Pb7ErpBct6bJSg-30ec/viewer?pli=1&f=0

Current Planning Doc:

https://docs.google.com/document/d/1h5iXJFuyRpPFU-BYHu7enPrAvcfkIYiIbsqQX8J-ugo/edit?usp=sharing

Currently accepted ideas:

I. Accessibility to Identity (Race, Gender, etc)
II. Accessibility to Responsive Design
III. Developer Orientation/How to Build a Lab 

## Subtasks

- [ ] Develop About, Reading, Exercise, Reinforcement, and Quiz ideas for Accessibility to Identity
- [ ] Develop About, Reading, Exercise, Reinforcement, and Quiz ideas for Accessibility to Responsive Design
- [ ] Develop About, Reading, Exercise, Reinforcement, and Quiz ideas for Developer Orientation/How to Build a Lab

## Acceptance Criteria

- [ ] [Acceptance Criteria 1]
- [ ] [Acceptance Criteria 2]
- [ ] [Acceptance Criteria 3]
