### ISSUE TITLE
Epic: Imagine 2023

### ISSUE THREAD

**Issue by heathermoses** [all-rit/ALL#486]
# Imagine 2023

## User Stories

List the user stories that are associated with this epic.

- [ ] As a Developer, I want to refactor and clean up imagine RIT db schema, so that it can be more easily used. #500 
- [ ] As a Participant, I want my Decisions in the Pre Survey to determine my activity , so that I have correctly collected data #501 
- [ ] As a Developer , I want Services to follow Current Practices, so the code better conforms with the teams style guide #link
- [ ] As a Developer, I want Controllers to follow Current so the code better conforms with the teams style guide
- [ ] As a Developer, I want to document and convert it to a pure component so it can be used in the ALL component Library.

## Technical Requirements

List the technical requirements for this epic.

- [ ] [Requirement 1]
- [ ] [Requirement 2]
- [ ] [Requirement 3]

## Design Considerations

List any special design considerations for this epic.

- [ ] [Consideration 1]
- [ ] [Consideration 2]

## Dependencies

List any epics that this epic depends on.

- [ ] [Epic 1]
- [ ] [Epic 2]

## Design Documents

List the design documents associated with this epic.

- [ ] [Document 1]
- [ ] [Document 2]
