### ISSUE TITLE
Epic: Lab 12 - Accessibility to Expression

### ISSUE THREAD

**Issue by AndreasLc1103** [all-rit/ALL#490]
# Accessibility to Inclusive Text Lab 12

This Epic will be responsible for being the single source of truth and tracking for the possible new lab #12. This lab is centered upon inclusive text and the impacts of using incorrect terminology.

## User Stories

List the user stories that are associated with this epic.

- [x] As a Developer, I want a clear and defined Wireframe, so that we can easily replicate it by hand. #link
- [x] As a ROLE, I want GOAL, so that REASON #link
- [x] As a ROLE, I want GOAL, so that REASON #link
- [x] #558 
- [x] #557 
- [x] #559 
- [x] #560 
- [x] #563 
- [x] #564 
- [x] #562 
- [x] #565 
- [x] #566 

## Technical Requirements

List the technical requirements for this epic.

- [x] [Requirement 1]
- [x] [Requirement 2]
- [x] [Requirement 3]

## Design Considerations

List any special design considerations for this epic.

- [x] [Consideration 1]
- [x] [Consideration 2]

## Dependencies

List any epics that this epic depends on.

- [x] [Epic 1]
- [x] [Epic 2]

## Design Documents

List the design documents associated with this epic.

- [x] [Document 1]
- [x] [Document 2]
