### ISSUE TITLE
Epic: Accessibility to Responsive Design Lab 13

### ISSUE THREAD

**Issue by AndreasLc1103** [all-rit/ALL#491]
# Accessibility to Responsive Design 

This epic is to act as the single source of truth for developing a lab to teach about the importance of creating Responsive front-end design. This lab will guide users through fixing issues with a non scalable view and how to fix them. 

## User Stories

List the user stories that are associated with this epic.

- [ ] As a ROLE, I want GOAL, so that REASON #link
- [ ] As a ROLE, I want GOAL, so that REASON #link
- [ ] As a ROLE, I want GOAL, so that REASON #link

## Technical Requirements

List the technical requirements for this epic.

- [ ] [Requirement 1]
- [ ] [Requirement 2]
- [ ] [Requirement 3]

## Design Considerations

List any special design considerations for this epic.

- [ ] [Consideration 1]
- [ ] [Consideration 2]

## Dependencies

List any epics that this epic depends on.

- [ ] [Epic 1]
- [ ] [Epic 2]

## Design Documents

List the design documents associated with this epic.

- [ ] [Document 1]
- [ ] [Document 2]

**Comment by JackyFTW** [comment]
Outdated
