### ISSUE TITLE
Epic: Testing Possibility Support

### ISSUE THREAD

**Issue by AndreasLc1103** [all-rit/ALL#492]
# Testing Possibility Support

This epic serves as a new initiative for bringing a more concise organization of the overall architecture of the project. Currently, this Epic will establish more developer-level control when trying to use resources within the project, mainly related to being connected to the production or staging server environments. 

## User Stories

List the user stories that are associated with this epic.

- [x] As a Developer, I want to have my database containerized, so that I can run code locally without having to ssh into another server #498 
- [ ] As a Developer, I want to be able to write unit tests, so I can test my code before reviewing #link
- [ ] As a Developer, I want the ability to be able to mock Database calls, so that there is the possibility to not need to use a database at all.  #link
- [ ]  As a Developer, I want tests to be automatically by pre-commit so I can't push failing test cases. 
- [ ]  As a Developer, I want to be able to run tests in the CI portion of the CI/CD pipeline, so I can ensure that code is in a stable state.

## Technical Requirements

List the technical requirements for this epic.

- [ ] [Jest Implementation](https://jestjs.io/)
- [ ] [Docker](https://www.docker.com/)

## Design Considerations

List any special design considerations for this epic.

- [ ] Decouple Database and Allow for mocking

## Dependencies

List any epics that this epic depends on.

- [ ] [Epic 1]
- [ ] [Epic 2]

## Design Documents

List the design documents associated with this epic.

**Comment by AndreasLc1103** [comment]
https://pankajconnect.medium.com/how-to-migrate-your-postgresql-database-to-docker-a-practical-guide-6014fb066b8f

https://docs.docker.com/engine/reference/builder/

https://www.docker.com/blog/how-to-use-the-postgres-docker-official-image/

https://www.docker.com/101-tutorial/

https://forums.docker.com/t/cant-connect-to-container-on-localhost-with-port-mapping/52716?page=2

https://wkrzywiec.medium.com/database-in-a-docker-container-how-to-start-and-whats-it-about-5e3ceea77e50

https://pankajconnect.medium.com/how-to-migrate-your-postgresql-database-to-docker-a-practical-guide-6014fb066b8f

**Comment by JackyFTW** [comment]
Outdated & duplicate of #609 now
