### ISSUE TITLE
Epic: Code Coverage Client

### ISSUE THREAD

**Issue by AndreasLc1103** [all-rit/ALL#494]
# Code Coverage For Client

This story is responsible for the development of test cases to improve code coverage of the front-end client.

## User Stories

List the user stories that are associated with this epic.

- [ ] As a ROLE, I want GOAL, so that REASON #link
- [ ] As a ROLE, I want GOAL, so that REASON #link
- [ ] As a ROLE, I want GOAL, so that REASON #link

## Technical Requirements

List the technical requirements for this epic.

- [ ] [Requirement 1]
- [ ] [Requirement 2]
- [ ] [Requirement 3]

## Design Considerations

List any special design considerations for this epic.

- [ ] [Consideration 1]
- [ ] [Consideration 2]

## Dependencies

List any epics that this epic depends on.

- [ ] [Epic 1]
- [ ] [Epic 2]

## Design Documents

List the design documents associated with this epic.

- [ ] [Document 1]
- [ ] [Document 2]
