### ISSUE TITLE
Epic: Lab 0

### ISSUE THREAD

**Issue by heathermoses** [all-rit/ALL#556]
# Lab 0

## User Stories

List the user stories that are associated with this epic.

- [ ] As a ROLE, I want GOAL, so that REASON #link
- [ ] As a ROLE, I want GOAL, so that REASON #link
- [ ] As a ROLE, I want GOAL, so that REASON #link
- [x] #561 

## Design Considerations

List any special design considerations for this epic.

- [ ] [Consideration 1]
- [ ] [Consideration 2]

## Design Documents

- https://drive.google.com/drive/folders/1VydIryuse20JtBVs7EtAIdsRGXMlkj_9?usp=drive_link
- https://docs.google.com/document/d/1ajm9uRRhoXFt59Q649T_AwxFDsJjFKgVuIohSKQjTGE/edit#heading=h.mwr80eebl2bw

**Comment by JackyFTW** [comment]
Reference new epic: #683
