### ISSUE TITLE
Epic: UI Refresh

### ISSUE THREAD

**Issue by heathermoses** [all-rit/ALL#619]
# UI Refresh

Figma: https://www.figma.com/design/aYxGokLEIXDBvMysJZVNNj/Branding-Package?node-id=0-1&node-type=canvas&t=Rol4am5tnPHXniBY-0

## User Stories

List the user stories that are associated with this epic.

- [x] As a Student, I want an updated, clean user experience, so that I want to use ALL on a regular basis
- [x] As a Teacher, I want an easy to use and follow design, so that my students can successfully complete assignments
- [x] As a University, I want to partner with ALL, so that our students can learn about accessible software in an easy to use environment

## Technical Requirements

List the technical requirements for this epic.

### Components
- [x] Update Nav Bar to New Styling: #620 
- [x] Update Lab Card To Include Difficulty and Certificate: #638 
- [x] Create Development Partners Grid: Story #636 
- [x] Create New Lab Table Navigation: #633 
- [x] Update Lab Buttons to new styling: #635 
- [x] Create New Universal Footer: #637 
- [x] Create New Universal ALL Modal: #639
- [x] #661
- [x] #656
- [x] #654
- [x] #655
- [x] Update Site Accessibility Settings button: #670 

### Pages
- [x] Create About Us Page: #634 
- [x] Refresh UI for Profile Page: #645 
- [x] Refresh Home Page: #651
- [x] Create New Labs Page: #652
- [x] Create Educator Resources Page: #653
